version: "3.3"
services:
  oauth2:
    image: ${SERVICE_IMAGE:-corntoole/oauth2-mock-server}:${IMAGE_TAG:-dev}
    build:
        context: .
        labels:
          zenoss.zing.commit-sha: ${COMMIT_SHA:-none}
          zenoss.zing.pull-request: ${PULL_REQUEST:-none}
          zenoss.zing.branch_name: ${GIT_BRANCH:-none}
          zenoss.zing.build_number: ${BUILD_ID:-none}
          zenoss.zing.build_url: ${BUILD_URL:-none}
    ports:
      - "3000:8080"
    # environment:
      # GRAPHQL_LOG_LEVEL: info
      # GRAPHQL_HTTP_PORT: 3000
      # ELASTIC_HOST: localhost:9200
      # NODE_OPTIONS: --max-http-header-size=81920

